[env:esp32_base]
platform  = espressif32
board     = m5stick-c-plus2
framework = arduino
monitor_speed = 115200
lib_deps  = m5stack/M5Unified @ ^0.1.12
build_flags = -std=gnu++17 -Wall -Iinclude -Ilib/HAL -Ilib/Algorithms

[env:wrist]
extends     = env:esp32_base
build_flags = ${env:esp32_base.build_flags} -DTARGET_WRIST
build_src_filter = +<wrist/>

[env:ankle_left]
extends     = env:esp32_base
build_flags = ${env:esp32_base.build_flags} -DIS_LEFT_ANKLE
build_src_filter = +<ankle/>

[env:ankle_right]
extends     = env:esp32_base
build_flags = ${env:esp32_base.build_flags} -DIS_RIGHT_ANKLE
build_src_filter = +<ankle/>